name: testPGDB

on: [push]

jobs:
  testPGDB:
      runs-on: {ubuntu-latest,   r: 'release'}
      env:
        PG_DB: ${{ secrets.PG_DB }}
      steps:
        - run: echo PG_DB=
        - run: echo $PG_DB
